### ISSUE TITLE
Colours don't work.

### ISSUE THREAD

**Issue by RaccoonClout** [Hexer10/HexTags#38]
https://gyazo.com/515bfd48db5e0e6c7afaf1a985bfbcab

Self explanatory.

**Comment by paulocrash** [comment]
Post your `sm plugins list`, it is probably some necessary plugin that is missing.

Remember to follow the plugin installation tutorial to the letter.

In order to install the plugin you need to:

1. Install properly [chat processor](https://forums.alliedmods.net/showthread.php?p=2448733).
2. Download the latest HexTags relase from the [releases page](https://github.com/Hexer10/HexTags/releases)
3. Merge the addons folder with the one in your server.
4. [Configure](https://github.com/Hexer10/HexTags/wiki/Configure-hextags.cfg) the plugin: hextags.cfg
5. Type `sm plugins load HexTags` (from rcon or console) / Change map / Restart the server to load the plugin.
